FROM python:2.7
ENV PYTHONUNBUFFERED 1

# Requirements have to be pulled and installed here, otherwise caching won't work
COPY requirements /requirements

RUN pip install -r /requirements/local.txt

COPY compose/flask/entrypoint.sh /entrypoint.sh
RUN sed -i 's/\r//' /entrypoint.sh
RUN chmod +x /entrypoint.sh

RUN mkdir -p /var/log/flixbus_api/

WORKDIR /src

ENTRYPOINT ["/entrypoint.sh"]
